package com.ghostofpq.kulkan.client.utils;

public enum TextureKey {
    GRASS, EARTH, HIGHLIGHT_BLUE, HIGHLIGHT_GREEN, HIGHLIGHT_RED, CHAR, TEXT_FIELD_FOCUS, TEXT_FIELD_NO_FOCUS, BUTTON_FOCUS, BUTTON_NO_FOCUS, LOGIN_BACKGROUND
}
