package com.ghostofpq.kulkan.client.utils;

public enum TextureKey {
    GRASS,
    EARTH,
    HIGHLIGHT_BLUE,
    HIGHLIGHT_GREEN,
    HIGHLIGHT_RED,
    CHAR,
    TEXT_FIELD_FOCUS,
    TEXT_FIELD_NO_FOCUS,
    BUTTON_FOCUS,
    BUTTON_NO_FOCUS,
    LOGIN_BACKGROUND,
    BACKGROUND_BASIC,

    LOBBY_BACKGROUND_169,
    LOBBY_CHAT_OVERLAY,
    LOBBY_NEWS_OVERLAY,
    LOBBY_CHAR_SHADOW,

    COMMON_EXT_FRAME,
    COMMON_BACKGROUND_BASIC,

    ACTION_1,
    ACTION_1_BACK,
    ACTION_1_HOVERED,

    EARTH_TOP_00,
    EARTH_TOP_01,
    EARTH_TOP_02,
    EARTH_TOP_03,
    EARTH_TOP_04,
    EARTH_TOP_05,
    EARTH_TOP_06,
    EARTH_TOP_07,
    EARTH_TOP_08,
    EARTH_TOP_09,

    EARTH_SIDE_00,
    EARTH_SIDE_01,
    EARTH_SIDE_02,
    EARTH_SIDE_03
}
